name: Update Player Data from Wikipedia

on:
  schedule:
    # Run every Monday at 2 AM UTC (weekly)
    - cron: '0 2 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r scripts/requirements.txt
    
    - name: Update player data from Wikipedia
      run: |
        python scripts/update-player-data.py
    
    - name: Check for changes
      id: git-check
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/data/players.csv
        git commit -m "chore: Update player data from Wikipedia [skip ci]" || exit 0
        git push

